use KuplyaevIntensive
GO
ALTER TABLE Tasks
	ADD CONSTRAINT FK_Tasks_Projects
	FOREIGN KEY (id_project) REFERENCES Projects (id_project)
        ON DELETE CASCADE
		ON UPDATE CASCADE
GO
ALTER TABLE TasksTags
	ADD CONSTRAINT FK_Tasks_TaskTags FOREIGN KEY (id_task) 
		REFERENCES Tasks (id_task)
		ON DELETE CASCADE
		ON UPDATE CASCADE
GO	
ALTER TABLE TasksTags
	ADD CONSTRAINT FK_Tags_TaskTags	FOREIGN KEY (id_tag) 
		REFERENCES Tags (id_tag)
		ON DELETE CASCADE
		ON UPDATE CASCADE